CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  contraseña VARCHAR(255) NOT NULL,
  fotoperfil VARCHAR(255) DEFAULT '',
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
